---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereDeploymentZone
metadata:
 name: dc01
 labels:
   region: region-cluster
   az: dc01
spec:
 server: vcsa.sample.net 
 failureDomain: dc01
 placementConstraint:
   resourcePool: TKG-CLUSTERS-RP01
